### ISSUE TITLE
url.parse() is broken

### ISSUE THREAD

**Issue by ChALkeR** [isaacs/natives#9]
```console
> var x = url.parse('http://example.org')
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.org',
  port: null,
  hostname: 'example.org',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://example.org/' }
> url.parse(x)
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'example.org',
  port: null,
  hostname: 'example.org',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://example.org/' }
> require('natives').require('url').parse(x)
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at repl:1:35
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:503:10)
```

**Comment by isaacs** [comment]
Huh. Yeah that's a bug.
